name: note163Checkin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 20 2 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
              python-version: 3.x

    # Runs a set of commands using the runners shell
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Checkin
      env:
            PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      run: |
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'           
        
        user_list=()
        pwd_list=()
        IFS=" "
        for u in ${user[*]}
        do
        user_list[${#user_list[*]}]=${u}
        done
        for p in ${pwd[*]}
        do
        pwd_list[${#pwd_list[*]}]=${p}
        done
        user_num=${#user_list[*]}
        pwd_num=${#pwd_list[*]}
        if [ $user_num != $pwd_num ];then
        echo "账号和密码个数不对应"
        exit 1
        else
        echo "共有 $user_num 个账号，即将开始签到"
        fi
        for ((i=0;i<$user_num;i++))
        do
        python3 note163.py <<EOF
        ${user_list[$i]}
        ${pwd_list[$i]}
        EOF
        done
